# Site
repository: WilliamRamirez/williamramirez.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: William Ramirez
title: Sharepoint Engineer
email: williammerlin@hotmail.com
website: www.github.com/williammerlin/williamramirez.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: willmx
github_username:  WilliamRamirez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: williamramirezsr
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#######additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #######url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Web developer with 3+ years of experience developing and supporting .Net web-based applications and vb.net webforms. SharePoint Online Administrator and SQL Server Reporting Services (SSRS) report writer and SQL Server Integration Services(SSIS) support and monitoring. I am driven individual with the ability to adapt to any situation and prove potential to learn the business and improve processes.
  I am most skilled in: <mark>Microsoft 365</mark> and <mark>.Net</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Sharepoint Migrations
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest projects ever worked, From Sharepoint on-premises to Sharepoint Online.
        description: | # this will include new lines to allow paragraphs
          Migrating the content from on-premises to production. Created and configured service applications. Configured the enterprise search and administrating the search service application.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Business Institute
        link: www.nbi-sems.com
        # link_text: boringcompany.com
        sub_title: Programmer Analyst/SharePoint Administrator
        caption: July 2018 - September 2020
        #quote: >
         # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            ● Created, configured, and administered SharePoint sites and user permission rights and trained users. Supporting daily
            operation and troubleshooting to solve technology issues.
            ● Repaired and solved critical production problems with a mix of debugging and replicating issue in development.
            ● Generated various Monthly, Quarterly, Bi-Yearly, Yearly reports by different type of reports using SSRS. Automated report
            delivery via email.
            ● Added Continue Education courses into SAP HR Success factors via API and created job to insert data load daily.
            ● Code several pages during site migration and recently. I created career opportunities page in company website that helped
            human resources recruitment, and the ability to create job postings and applicants to upload resumes and cover letters.
            ● Migrated Legacy ASP intranet application to MVC 4.5 and added new functionality to improve business processes.
            ● Code, debug, test, and implement solutions in .NET environments using Visual Studio and related tools
            ● Strong object-oriented approach to programming with a focus on code-reuse, readability, and stability
            ● Added Continue Education courses into SAP HR Success factors via API and created job to insert data load daily.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Chippewa Valley Tecnical College
        caption: 2016 - 2018
        sub_title: Software Developer
        quote: >
        Best program in the Chippewa Valley
        description: | # this will include new lines to allow paragraphs
          During my time at CVTC I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Reading
      - Mounting computer hardware
      - Playing software
      - Biking
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #this  
   #   ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
